weights: ./work_dir/recognition/ours/ST_GCN_1121/epoch500_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/ours/xsub/val_data.npy
  label_path: ./data/ours/xsub/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 24
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ours'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 1

